// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3CkXj1rDLoSgHfJ0CgB7GGEjyoHccQMA',
    appId: '1:443367167345:web:99b44c50e56d5203c852d0',
    messagingSenderId: '443367167345',
    projectId: 'retorki-feladatkezelo',
    authDomain: 'retorki-feladatkezelo.firebaseapp.com',
    storageBucket: 'retorki-feladatkezelo.firebasestorage.app',
    measurementId: 'G-HZXC0MN29D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhACmo45lNvxt8O7gBPxaoEJeVLgXZck0',
    appId: '1:443367167345:android:5b3fc4c98108cbf5c852d0',
    messagingSenderId: '443367167345',
    projectId: 'retorki-feladatkezelo',
    storageBucket: 'retorki-feladatkezelo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBClyXeeFKuas_0ONGAbIUNV6s5thCwYak',
    appId: '1:443367167345:ios:abfd7ba7aaec52e1c852d0',
    messagingSenderId: '443367167345',
    projectId: 'retorki-feladatkezelo',
    storageBucket: 'retorki-feladatkezelo.firebasestorage.app',
    iosBundleId: 'com.example.dreamflow',
  );
}
